version: '3.8'
services:
  freqtrade:
    # image: freqtradeorg/freqtrade:stable
    # Build step - needed to install Pymongo
    build:
      context: "./freqtrade"
      dockerfile: "./Dockerfile"
    container_name: Freqtrade-Aurox
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./freqtrade/user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    ports:
      - "8080:8080"
    # Downloads historical candle data for the pairs in the config whitelist.
    # -t 15m 30m 1h 4h 12h 1d will download the data for each of those timeframes listed
    command: >
      download-data
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --config /freqtrade/user_data/config.json
      -t 15m
      --timerange 20210101-20210610
